site_name: ArmA 3 - ACE Guides
theme:
  name: material
  logo: assets/Icon.png
  favicon: assets/favicon.png

  palette:
    - scheme: default
      primary: darkred
      accent: amber
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode
    - scheme: slate
      primary: darkred
      accent: amber
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode

  icon:
    repo: fontawesome/brands/github

repo_name: royrovp/ArmA-3-Guides
repo_url: https://github.com/royrovp/ArmA-3-Guides

markdown_extensions:
  # For adminitions
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.details # For collapsable admonitions - see https://squidfunk.github.io/mkdocs-material/reference/admonitions/?h=%3F%3F%3F#collapsible-blocks

  # For Abbreviations
  - abbr
  - pymdownx.snippets
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons

plugins:
  - search
  - awesome-pages # For reordering pages so modders have a clear progression for understanding
